// <auto-generated />
using AlicIA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AlicIA.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AlicIADbContext))]
    [Migration("20260410120000_AddTenantSlug")]
    public partial class AddTenantSlug
    {
    }
}
